"""embed_asset.py — turn a real .css/.js/.svg file into a C++ header.

WHY THIS EXISTS. `site_css()` was 531 lines of CSS and `site_js()` was 285 lines
of JavaScript, both living inside C++ raw-string literals. That meant no syntax
highlighting, no linter, no formatter, no way for an editor to tell you a brace
was unbalanced — in two languages that are hard enough to get right with tools.
It also meant escaping hazards: a stray sequence inside a literal bit this
project once already.

Now they are real files under `src/render/web/`, edited as CSS and JavaScript,
and embedded at build time. **The binary stays exactly as self-contained as
before** — nothing is read at runtime, nothing is fetched from a network. The
only thing that changed is which program can understand the file.

Emits a `char[]` rather than a `std::string` so the data lands in .rodata and
costs no static initialiser.

    python tools/embed_asset.py <input> <output.hpp> <symbol>
"""
import os
import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write(__doc__)
        return 2
    src, dst, symbol = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(src, "rb") as f:
        data = f.read()

    # Chunked hex escapes rather than a raw string: a raw string would break the
    # moment the asset contained the closing delimiter, and MSVC caps a single
    # string literal at 16380 bytes — which style.css already exceeds.
    out = []
    out.append("/* GENERATED by tools/embed_asset.py from %s — do not edit.\n"
               " * Edit the source file and rebuild. */\n"
               % os.path.basename(src).replace("*/", ""))
    out.append("#pragma once\n\n")
    out.append("inline constexpr char %s[] = {\n" % symbol)
    line = "   "
    for i, b in enumerate(data):
        # an explicit cast: a UTF-8 byte above 0x7F does not fit a signed
        # char, and a bare 0xE2 in a braced initialiser is a narrowing
        # error. These assets are UTF-8 (em-dashes, accented Spanish), so
        # that is the common case rather than an edge one.
        line += " (char)0x%02x," % b
        if len(line) >= 66:
            out.append(line + "\n")
            line = "   "
    if line.strip():
        out.append(line + "\n")
    out.append("    (char)0x00\n};\n")
    out.append("inline constexpr int %s_len = %d;\n" % (symbol, len(data)))

    text = "".join(out)
    # Only rewrite when the content actually changes, so an unchanged asset does
    # not force every dependent translation unit to recompile.
    if os.path.exists(dst):
        with open(dst, "r", encoding="utf-8", newline="") as f:
            if f.read() == text:
                return 0
    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    with open(dst, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
